### ISSUE TITLE
Use on Windows (PowerShell)

### ISSUE THREAD

**Issue by xmha97** [Gbox4/tstock#10]
How I can add my API key on Windows?
![image](https://user-images.githubusercontent.com/23485114/151716041-bdbc6fd7-d3b5-466e-8dc1-b2b605c37cdd.png)

**Comment by xmha97** [comment]
![image](https://user-images.githubusercontent.com/23485114/151716605-ca4d2043-5beb-4aef-b6ab-0fc9234f7bb2.png)

**Comment by Gbox4** [comment]
Fixed with commit bded09ed42bb902d7c8ef92627cb27b483348c67. Note that the default cmd and PowerShell terminals don't display ANSI escape sequences properly. You'll need to use a terminal like Windows Terminal to properly display colors.
