### ISSUE TITLE
Cannot print the graph in Windows Bash

### ISSUE THREAD

**Issue by rameshKrSah** [Gbox4/tstock#11]
hi, I am using Git Bash and after installing ```tstock``` with pip and setting the Alphavantage API key (for anyone interested in how to do this see [here](h)) the program fails to print out the graph. 

I am getting ```UnicodeEncodeError: 'charmap' codec can't encode characters in position 7-8: character maps to <undefined>``` error. i have attached the screenshot below. Looks like the error is at line 379 from ```core.py``` and it might need fixing by forcing UTF-8 encoding ( I am not sure). 

![image](https://user-images.githubusercontent.com/21354640/151720510-f4bfb687-ee0f-4122-8d42-ff54753de616.png)

**Comment by Gbox4** [comment]
Yeah, Git Bash has a lot of limitations. I'm trying but can't replicate the behavior described. Maybe try using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install) instead? I don't really plan to add support for Git Bash, but if you come up with a solution, please feel free to make a PR :)
