### ISSUE TITLE
Not draw well on Termux (Android)

### ISSUE THREAD

**Issue by xmha97** [Gbox4/tstock#20]
Hi, I want to use tstock on Termux (Android).

# Landscape

![Screenshot_2022-02-04-15-06-13-046_com termux](https://user-images.githubusercontent.com/23485114/152523468-35cdaed3-1e4b-403c-b63b-2ddc3fe91215.jpg)

# Portrait

![Screenshot_2022-02-04-15-05-47-433_com termux](https://user-images.githubusercontent.com/23485114/152523460-d46594d2-b445-4af2-9419-0318b23053a8.jpg)

**Comment by Gbox4** [comment]
Try using the -b option to reduce the x-scale of the graph. `tstock -b 50` for example.

**Comment by xmha97** [comment]
Ok, thanks.
Please add the `auto` parameter:
```
tstock -y auto -b auto aapl
```

**Comment by Gbox4** [comment]
Good idea, I implemented it in commit 8bfec8d7b2e52e8f2d549b975b086d20a89b0b85

**Comment by xmha97** [comment]
Thanks.
