### ISSUE TITLE
Sharp spikes cause graph to be disconnected

### ISSUE THREAD

**Issue by Samuel3k** [Gbox4/tstock#21]
Maybe just a limitation, but it would be nice if it's fixable.
![Screenshot from 2022-02-03 23-36-25](https://user-images.githubusercontent.com/53394877/152557222-616ef3da-8171-4b26-904d-78692fb3c470.png)

**Comment by Stock84-dev** [comment]
This is not a bug, FB actually fell 27%. Stocks can have gaps between days.

**Comment by Gbox4** [comment]
Just to add on, you can see that this is just the way candlestick charts work. Here is a screenshot of the Yahoo Finance chart, the last day also has a gap.
![image](https://user-images.githubusercontent.com/48675187/152560331-44b68ca1-4bd3-457b-8c5e-386d53fa5c49.png)

**Comment by Samuel3k** [comment]
Ah I see. Should've informed myself better on how this kind of chart works, my apologies.
